### ISSUE TITLE
Request for ability to upload the files to Google drive via rclone

### ISSUE THREAD

**Issue by krishne35** [maple3142/heroku-aria2c#1]
Once the files downloaded later gets uploaded to gdrive will be handy

**Comment by bnichs5** [comment]
I would also like to see this. +1

**Comment by maple3142** [comment]
I think it is not possible, because heroku doesn't have FUSE, which is needed by `rclone mount`.

**Comment by krishne35** [comment]
Need not to mount you can you rclone copy command

**Comment by krishne35** [comment]
As seen in this https://gitlab.com/mega036/aria2cloud-colab/tree/master/.aria2 
Or you could just use Google drive API to upload the files to gdrive

**Comment by maple3142** [comment]
This feature has been implemented.
