### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by 135e2** [maple3142/heroku-aria2c#12]
大佬好，请问能否修改rclone使之支持OD世纪互联？

以及再问一下，下载过程中如果超过了自动休眠时间30min是否会停止？
还是我需要设置网站监控保持活跃？

**Comment by maple3142** [comment]
第一個問題我不曉得
第二個問題是不用，因為我有設定讓他在下載及上傳時會自動避免休眠

**Comment by 135e2** [comment]
Ok，谢谢大佬
