### ISSUE TITLE
请问可以添加对于世纪互联版的onedrive支持吗？

### ISSUE THREAD

**Issue by zhaoyang1993** [maple3142/heroku-aria2c#14]
请问可以添加对于世纪互联版的onedrive支持吗？

我目前是通过https://peachcat.org/?p=996 和 https://www.hostloc.com/forum.php?mod=viewthread&tid=612579 这两个帖子在尝试

**Comment by maple3142** [comment]
OneDrive的支援功能都是透過rclone來提供的，請直接向rclone的作者詢問

**Comment by xinxin8816** [comment]
我的分支已实现相关功能：https://github.com/xinxin8816/heroku-aria2c-21vianet
