### ISSUE TITLE
下载后的文件如何删除

### ISSUE THREAD

**Issue by 666wcy** [maple3142/heroku-aria2c#16]
想把上传的文件移动，但是本地的文件不删除又会重新上传，还有请问支持下载文件的大小是多大，谢谢！

**Comment by maple3142** [comment]
不用刪除，休眠時會自己消失
上傳時也不會重新上傳
下載的最大大小我也不知道

**Comment by fanweiya** [comment]
是否可以考虑集成这些脚本，谢谢！
https://github.com/ondh/aria2rss
https://github.com/P3TERX/aria2.conf
