### ISSUE TITLE
Onedrive的token使用一小时后就会过期

### ISSUE THREAD

**Issue by djdic** [maple3142/heroku-aria2c#17]
Rclone挂载Onedrive获取的access token会在获取一小时后过期，再部署完成后的第一个小时能够正常同步，过期后就无法通过rclone同步文件到onedrive，在logs里会显示
“Failed to create file system for "DRIVE:/XXX(同步的文件夹）": failed to get root: InvalidAuthenticationToken: Access token has expired.”
这时候也没办法修改填入的rclone conf,只能重新deploy,有没有什么解决办法

**Comment by maple3142** [comment]
rclone的問題請找rclone，因為那不是這個專案負責的部分
