### ISSUE TITLE
(Question) is it possible to save ALL settings on restart?

### ISSUE THREAD

**Issue by eliasbenb** [maple3142/heroku-aria2c#25]
Is it possible to make it so that the Aria2 settings and AriaNG settings automatically are set to a customized setting on restart?

**Comment by maple3142** [comment]
@eliasbenb No, there is no simple persistent tool to store state, so it is recommended to fork this repo, modify configuration and push to Heroku if you need extra customization.

**Comment by eliasbenb** [comment]
@maple3142 thanks for the really quick reply. What I wanted to change was the setting that makes the app redownload a file if I move/delete the file from Google Drive. Could you tell me the name of the setting? Thanks again

**Comment by maple3142** [comment]
@eliasbenb Redownload?

**Comment by eliasbenb** [comment]
> @eliasbenb Redownload?

Yes it redownloads/reuploads it to the place where I deleted/moved the file from

**Comment by maple3142** [comment]
@eliasbenb No, it is basically impossible to do so with hugely change this project, you can fork it and implement it by yourself if you really want.

**Comment by eliasbenb** [comment]
> @eliasbenb No, it is basically impossible to do so with hugely change this project, you can fork it and implement it by yourself if you really want.

Are you sure? I'm looking through the settings right now, it seems like the setting that causes this problem is either one of these:
allow-overwrite
save-not-found

I'll test it by turning one of them off and seeing if the app redownloads/reuploads it.
Will report back, thanks

**Comment by maple3142** [comment]
@eliasbenb Uploading is handled by rclone, where aria2c's config has nothing to do with.

**Comment by eliasbenb** [comment]
> @eliasbenb Uploading is handled by rclone, where aria2c's config has nothing to do with.

I don't think so, I just updated the two settings I was talking about and I set them to false, the issue hasn't happened for the last 10 minutes. But I'll wait a little longer before confirming.

**Comment by eliasbenb** [comment]
So I left the app for about half an our, everything was fine, the files weren't being reuploaded. But then I started downloading a new file (seperate to the one from half an hour ago) and the original file from half an hour ago was reuploaded.

Turning off allow-overwrite and save-not-found didn't fix the issue.

You must be right about the issue being with rclone, thanks for the help, I'll close the issue now.
