### ISSUE TITLE
功能增强--添加Server chan通知

### ISSUE THREAD

**Issue by cxyzzz** [maple3142/heroku-aria2c#27]
[Serverchan](http://sc.ftqq.com/3.version)
下载完成后无法看到上传进度也就不知道什么时候上传完，添加Server chan可以在传完后发送通知，并且也只需要token就来发送，可以在部署是添加环境变量。

**Comment by maple3142** [comment]
上傳是否完成可以透過檢查 heroku 的 log 來知道
再來，我並沒有用微信，所以那個對我完全沒用
