### ISSUE TITLE
Onedrive upload is too much slow 

### ISSUE THREAD

**Issue by bnsave100** [maple3142/heroku-aria2c#32]
It's been a month now I saw very high difference in upload speed of rclone to onedrive I don't know if this is happening only with me or everyone please help previously I use to upload big files so easily but now it takes almost a day for same size 
 e.g. 50gb

**Comment by maple3142** [comment]
I don't know, it is a problem on heroku side.

**Comment by mohitjoshi155** [comment]
ya same issue

**Comment by bnsave100** [comment]
I checked logs speed is in bytes shows so many days

**Comment by guardapi** [comment]
same issue! 500mb file uploaded in 90 min!
