### ISSUE TITLE
Found why onedrive upload is slow !!

### ISSUE THREAD

**Issue by bnsave100** [maple3142/heroku-aria2c#33]
Well when we download a single file or so many different files not a whole bunch with a folder rclone does it better when it uploads to onedrive speed is upto 8 to 10mbps
But when we upload a folder having so many files rclone uploads files in batches of 4 (As I have observed in logs) so the speed is divided and uploads become slow before completing one batch it starts 2nd one as a process and there speed is in kbps 

So those who know coding is there any way to 
1. Make rclone upload files one by one and not in batches 
2. Determine upload chunk at one time or the limit of upload at one time 

Either of this can solve the issue if it's possible to do with rclone I mean with commands that can put this in process 
So if anyone know such commands or solutions please contribute

**Comment by bnsave100** [comment]
Update: rclone officially transfers 4 files at a time to change this we have to use --transfers=X
"X"= number of parallel transfers at a time 

But how to do it on heroku??????????????

**Comment by maple3142** [comment]
Learn git, heroku and bash
Then clone this repo, modify the command, push it to heroku

For me, transfers=4 is faster

**Comment by usmanmughalji** [comment]
You can try shared team drive though instead of one drive @bnsave100. i also have tested one drive with bot on telegram uploading to one drive is slow but not that kind of slow. I think you can give try to shared team drive.

**Comment by mohitjoshi155** [comment]
> 
> 
> Update: rclone officially transfers 4 files at a time to change this we have to use --transfers=X
> "X"= number of parallel transfers at a time
> 
> But how to do it on heroku??????????????

can u fork the repo and modify specially for onedrive?

**Comment by bnsave100** [comment]
> > Update: rclone officially transfers 4 files at a time to change this we have to use --transfers=X
> > "X"= number of parallel transfers at a time
> > But how to do it on heroku??????????????
> 
> can u fork the repo and modify specially for onedrive?

I wish I could but I'm not coder 😅😅

**Comment by gautamajay52** [comment]
> > Update: rclone officially transfers 4 files at a time to change this we have to use --transfers=X
> > "X"= number of parallel transfers at a time
> > But how to do it on heroku??????????????
> 
> can u fork the repo and modify specially for onedrive?

I can modify the code for --transfer=X, but I can't check.

If u want u can contact me on telegram(same username).
