### ISSUE TITLE
Upload to Google teamdrive with aria 

### ISSUE THREAD

**Issue by bnsave100** [maple3142/heroku-aria2c#37]
Is it possible to upload to Google teamdrive with aria2 
I have made rclone config including team drive just don't konw what should be path for teamdrive to put in aria rclone_destination

**Comment by mohitjoshi155** [comment]
u can refer my guide here:-
https://telegra.ph/Make-your-own-Aria2-Torrent-Leecher-Supports-Direct-upload-to-GsuiteTDOnedrive-etc-04-26

**Comment by bnsave100** [comment]
Got it
