### ISSUE TITLE
is it only me, heroku suddenly restarts app 

### ISSUE THREAD

**Issue by bnsave100** [maple3142/heroku-aria2c#39]
It been a week I don't know why but heroku is restarting apps while running, when app doesn't get any web request it's bound to sleep but when the process is going on why this is happening 
Issue is not related to app I know but still asking if anyone's facing this and if then does anyone have solution 
(I tried https://kaffeine.herokuapp.com/ 
Which keeps app awake by sending requests aria ran only for about 4hrs after that suddenly restarted don't know why )

**Comment by maple3142** [comment]
Yes, it is expected
