### ISSUE TITLE
Error when deploying via docker

### ISSUE THREAD

**Issue by em108** [maple3142/heroku-aria2c#40]
Hello, could the command to deploy on a machine to self host be up to date? Nothing seems to happen the I run the following command `docker-compose -d -f docker\docker-compose.yml up` as directed from [here](https://github.com/maple3142/heroku-aria2c/tree/master/docker) after installing all the necessary requirements. The only output from the system is the 'correct syntax' on how to use the command and help info on how to run the command but nothing else happens. 
Running on _OS: Ubuntu 18.04_

**Comment by maple3142** [comment]
Docker is just for testing, to use you need to do it yourself.
