### ISSUE TITLE
Delete files in heroku

### ISSUE THREAD

**Issue by YuutaDoNo** [maple3142/heroku-aria2c#41]
Is there any way to delete the files in heroku? Can't delete by ariang.

**Comment by maple3142** [comment]
@YuutaDoNo Just let it idle

**Comment by herokulogin52** [comment]
> Is there any way to delete the files in heroku? Can't delete by ariang.

Goto heroku---ur app----more--- and restart all dyno.
It will delete the Downloaded file and u can download again.

**Comment by gautamajay52** [comment]
> Is there any way to delete the files in heroku? Can't delete by ariang.

Go to heroku.com----ur app----more----and restart all dynos.
Then It will erase all the Downloaded files from heroku and u can download again
