### ISSUE TITLE
Unfinished torrent downloads 

### ISSUE THREAD

**Issue by abretas** [maple3142/heroku-aria2c#48]
Hi maple3142 could you help me?

I have implemented yourAria2 Torrent Leecher but i noticed that some torrent files that I put does not appear to download progress. In fact, it looks as if there was no download.

So after a while when I look at the folder I set up to be saved, the files are there.

My problem is that I have downloaded courses for my TD and some courses are not being rendered by google drive. Even when I download it to my computer it looks like the video is corrupted.

Some courses work and others don’t.

I will put some screens that what´s happen with me.

https://prnt.sc/se7ful

The files have been downloading for over an hour.
However when I enter my TD they appear, only if I download a video to my computer I cannot run it.

https://prnt.sc/se7hrf

**Comment by baba2580** [comment]
https://github.com/xinxin8816/heroku-ariang-21vianet

**Comment by baba2580** [comment]
Cannot GET /downloads/YmFiYTFAaGVyb2t1/

**Comment by maple3142** [comment]
@baba2580 wrong password

**Comment by baba2580** [comment]
https://github.com/xinxin8816/heroku-ariang-21vianet
i put correct password but also Error
Cannot GET /downloads/YmFiYTFAaGVyb2t1/

**Comment by maple3142** [comment]
@baba2580 If you are using that, don't ask questions here.

**Comment by webdev111** [comment]
hey there even after the downloads are complete the temp aria2 files are still copied in the destination..
what is the fix??

**Comment by maple3142** [comment]
I don't have this problem, so no fix. And don't be so entitled.

**Comment by webdev111** [comment]
thats ok..since i am new of aria2 i thought there might be some config that's doing this...
and maybe that "what is the fix?" made u thing about the "entitled" thing..what i actually meant was *is there a fix?
