### ISSUE TITLE
Token time

### ISSUE THREAD

**Issue by chammiii** [maple3142/heroku-aria2c#49]
How to increase token time?

**Comment by maple3142** [comment]
@chammiii ？

**Comment by chammiii** [comment]
Please help for increase token time. No file transfer to my team drive after token time get over.

**Comment by maple3142** [comment]
?

**Comment by chammiii** [comment]
i made heroku app at 12:10 pm. File transfer time only 2 hrs. Now files not transfer to team drive

**Comment by maple3142** [comment]
I don't understand what you are saying.

**Comment by chammiii** [comment]
I made a heroku app with above button. I created rclone config. In the rclone config, the token access time limit was only 2 hrs. I used that app 3 hrs for file transfer from web address to my team drive. After 2 hrs of using, no file transfer to my team drive while aria2 showed download completed. I checked heroku log in my application. There was an error about - your access token is expired.
Now how can I increased the access token?

**Comment by chammiii** [comment]
token_type":"Bearer","expiry":"2020-05-11T11:52:02.980076497+07:00"} team_drive = xxx

**Comment by maple3142** [comment]
I didn't have that problem

**Comment by gautamajay52** [comment]
> token_type":"Bearer","expiry":"2020-05-11T11:52:02.980076497+07:00"} team_drive = xxx

Put ur team_drive=xxxx above the token line.
And try.
