### ISSUE TITLE
Rclone copy fails after a period of time

### ISSUE THREAD

**Issue by Newbie-ctrl** [maple3142/heroku-aria2c#57]
Hi, thank you for creating this easy to use system. I am familiar with rclone but not much of a coder so I can't fix this issue I keep running into.
Everytime I deploy, everything works fine but after a couple hours, new downloads finish okay but don't move over to my gdrive/rclone config destination. The same config works fine on my local system and like I said it copies over everything great during the first hours of deployment but seems to stop accessing after a while, even after I restart the heroku-app (it stops before that) it doesn't fix the problem . I don't move or remove any files, all I do is add links and let the downloads finish. Please could anything be done to troubleshoot my issue?

**Comment by maple3142** [comment]
I don't have this problem, so no.

**Comment by fzfile** [comment]
> Hi, thank you for creating this easy to use system. I am familiar with rclone but not much of a coder so I can't fix this issue I keep running into.
> Everytime I deploy, everything works fine but after a couple hours, new downloads finish okay but don't move over to my gdrive/rclone config destination. The same config works fine on my local system and like I said it copies over everything great during the first hours of deployment but seems to stop accessing after a while, even after I restart the heroku-app (it stops before that) it doesn't fix the problem . I don't move or remove any files, all I do is add links and let the downloads finish. Please could anything be done to troubleshoot my issue?

Did you solve this issue? I met the same issue @Newbie-ctrl

**Comment by shakilofficial0** [comment]
OKH I Am Giving a Solve

Just Make a New Rclone config And Replace the old one from heroku.
I think it is Token Expire Problam on google
