### ISSUE TITLE
can't able to see download files in my drive

### ISSUE THREAD

**Issue by HITLER-KILLER** [maple3142/heroku-aria2c#60]
hey i am not to get able to see files in my drive after downloading and when i always launch the app it always need aria secret and i am not able to do the 3rd point given because i did't understand 

Find the drive you want to use, and copy its type = ... to ... token = ... section.
please reply me as soon as possible

**Comment by HITLER-KILLER** [comment]
why are closing man just tell me how to do it

**Comment by HITLER-KILLER** [comment]
if you are on telegram please tell me on it

**Comment by maple3142** [comment]
No
You aren't entitled to my help.
