### ISSUE TITLE
能添加个解压上传？

### ISSUE THREAD

**Issue by ldxw** [maple3142/heroku-aria2c#7]
rt ，
还有 能支持 萌咔的上传脚本吗？

**Comment by maple3142** [comment]
？？？

**Comment by ldxw** [comment]
> ？？？
这个上传脚本呢？
[https://github.com/MoeClub/OneList/tree/master/OneDriveUploader](url)
能支持吗？

**Comment by maple3142** [comment]
這個只支援rclone而已，而rclone也支援onedrive

**Comment by ldxw** [comment]
> 這個只支援rclone而已，而rclone也支援onedrive

这玩意过一会就重启，文件都没有 太特么玄学了 别r人的很久 我这就一会。。太大的好像上传不上。。

**Comment by maple3142** [comment]
這個會重啟是正常的，只要三十分鐘沒有request進入就會重啟

**Comment by ldxw** [comment]
那就要一直保证有文件在下载？

**Comment by maple3142** [comment]
你有必要讓他在你沒下載的時候也開著嗎？

**Comment by ldxw** [comment]
那在上传的时候停止了，不就玩完了。。

**Comment by maple3142** [comment]
你可以試著重新deploy，使用最新版的
我已經加入了上傳時的重啟保護了

**Comment by ldxw** [comment]
> 你可以試著重新deploy，使用最新版的
> 我已經加入了上傳時的重啟保護了

能看到上传列表吗？不然不清楚到底上传完了没有。。

**Comment by maple3142** [comment]
只能去log看
