### ISSUE TITLE
Using up free dyno hours even if not in use.

### ISSUE THREAD

**Issue by onoakino** [maple3142/heroku-aria2c#72]
Hi. I would just want to know how to fully stop all processes such that the dyno would not consume dyno hours even if not in use. The last time I used my app, I still have about 400 hours of dyno hours remaining. I downloaded a torrent, took me about an hour to finish. Then closed the tab. I assume it stopped consuming the hours after all the downloads are finished as well as closing the aria web interface tab. I just found out today that I maxxed out all my remaining hours for the month. I must be missing something here. Is there a switch I would have to click to fully turn off my dyno and let it sleep and not consume my free hours?

**Comment by maple3142** [comment]
I don't know
