### ISSUE TITLE
Unable to select and unselect files before downloading

### ISSUE THREAD

**Issue by askfriends** [maple3142/heroku-aria2c#75]
hi..
this is very nice and working script, enjoying it since many days.
but i came across an issue where i want to download only particular file in torrent but there is no any option to choose what files to download and what not to.
i tried to save torrent file to start later, that brought the torrent to "waiting" area, i saw files tab there but when i tried to unselect some files they got selected again automatically, so i cant do anything there too.

so please can you ad option to choose files before downloading?

Also it would be nice if you could add option to make zip/tar or any compression option before saving to gdrive. it will help to make folders zip and easy to copy/move/share around.

**Comment by maple3142** [comment]
No.
I can't add it.
