### ISSUE TITLE
Dont deploy it.

### ISSUE THREAD

**Issue by venom3525** [maple3142/heroku-aria2c#77]
Was good while it lasted.
![image](https://user-images.githubusercontent.com/66626095/89658696-92818800-d8ee-11ea-86ed-3369279cc380.png)

**Comment by MasterBrian99** [comment]
same here.....i got ban

**Comment by maple3142** [comment]
You probably overuse it, as I haven't get this.

**Comment by mohitjoshi155** [comment]
> 
> 
> You probably overuse it, as I haven't get this.

It is banning for new deployments...old ones r still running.... thats why

**Comment by maple3142** [comment]
@mohitjoshi155 Then it is still not a problem without my project.

**Comment by venom3525** [comment]
> You probably overuse it, as I haven't get this.

@maple3142 existing ones work. 
You will lose your account in  30 sec if you deploy it now.

**Comment by maple3142** [comment]
Added new instruction.
