### ISSUE TITLE
Direct open AriaNG panel instead of main page.

### ISSUE THREAD

**Issue by viper-adnan** [maple3142/heroku-aria2c#84]
Hi, I want to Directly open the AriaNG panel instead of the main page where I have to enter the password and the downloaded file option.
Because everyone can access my AriaNG panel without entering the password all he want is my heroku app name and then open the following URL
`https://<herokuappname>.herokuapp.com/ariang/#!/settings/rpc/set/wss/add.vipercloud.ga/443/jsonrpc/MA==`

So, I want to just skip the process which is asked in the root of the domain. Because everyone using it via rclone so we don't need the `Downloads` option.
I just want to do it in my repo anyone can open a pull request in my [`fork`](https://github.com/viper-adnan/heroku-aria2c) or tell me what to edit in [`index.js`](index.js). I didn't know much about node.js.

**Comment by maple3142** [comment]
You need to set your secret as password.

**Comment by viper-adnan** [comment]
I don't want that main page.

**Comment by maple3142** [comment]
You can't
