### ISSUE TITLE
tutorial video

### ISSUE THREAD

**Issue by AdzeB** [maple3142/heroku-aria2c#86]
Hello, l wanted to know if we could get a video on how to deploy with the new way?

Thanks in advance

**Comment by maple3142** [comment]
No, you are expected to figure it out yourself

**Comment by baba2580** [comment]
Any new way deploy Aria2 app on heroku.
Cause heroku is suspending account.
So what is way to deploy Aria2 app on heroku now.

Regards
Baba

**Comment by maple3142** [comment]
@baba2580 Read the readme
