### ISSUE TITLE
getting error while deploying after recent update

### ISSUE THREAD

**Issue by askfriends** [maple3142/heroku-aria2c#87]
hi..

first of all thanks a ton for updating this repo and make it alive again.

i am deploying it, but after i use command
` heroku container:push web -a app_name`

 it gives me error
` No images to push `
how to fix it?

btw i have git cloned on windows 10, i also run that command you have mentioned to run it on windows.

**Comment by maple3142** [comment]
Try running `docker built . -t heroku-aria2c` before push.

**Comment by askfriends** [comment]
> Try running `docker build . -t heroku-aria2c` before push.

i got this error now
```
'docker' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by maple3142** [comment]
See the requirements stated in README. You need docker.

**Comment by askfriends** [comment]
> Try running `docker build . -t heroku-aria2c` before push.

yeah i have installed docker and this command now runs, but i dont know why i am unable to get that command run successfully, it haults in the middle. my internet is also having issues so may be thats the reason but i am still unable to run that command successfully, can you help me in this regard?
here is screenshot where im stuck
![mapple](https://user-images.githubusercontent.com/2517219/92410779-a3782000-f15e-11ea-81b1-1181025455f2.png)
![mapple2](https://user-images.githubusercontent.com/2517219/92410884-12ee0f80-f15f-11ea-969b-f6090aa9e349.png)

**Comment by maple3142** [comment]
You need to wait for it, as it takes long time in this step.

**Comment by askfriends** [comment]
> You need to wait for it, as it takes long time in this step.

hasnt worked for me yet, contineously trying from last two days..i know its not your fault nut can you help me push that? i will send you credentials via email or telegram..

**Comment by maple3142** [comment]
No, you need to do it yourself.
