### ISSUE TITLE
部署到heroku config:set -a APP_NAME RCLONE_CONFIG=THAT_TEXT这一步时出现错误，请大佬指教！

### ISSUE THREAD

**Issue by phylis92857388** [maple3142/heroku-aria2c#89]
rclone config设置不管是否添加client_id和client_secret均出现错误，添加了client_id和client_secret则出现drivenclient_id is invalid. Must be in the format FOO=bar.
不添加client_id和client_secret则出现drivenscope is invalid. Must be in the format FOO=bar.
请大佬帮着看看指教下，是不是我的换行符写法有错误？小白什么都不懂。错误图片：
https://pan.cngas.tk/0:/Images/HeroKU/heroku.png

**Comment by maple3142** [comment]
要用雙引號括起來

**Comment by phylis92857388** [comment]
OK,谢大佬指点，已经部署成功，话说大佬的答复速度真快。
