### ISSUE TITLE
大佬，求问一下若后续想修改配置，即env的内容，应该怎么操作呢？

### ISSUE THREAD

**Issue by Ecalose** [maple3142/heroku-aria2c#93]
在原先是可以通过在线修改Config Vars解决，现在用cli应该怎么办呢？

**Comment by maple3142** [comment]
改 env 檔，重新啟動

**Comment by Ecalose** [comment]
> 改 env 檔，重新啟動

大佬，求问一下，修改env后，应该怎么用cli上传更改呢，我试过readme那两个命令，貌似不行，还是直接通过heroku网页版的consle台进行在线修改？

**Comment by maple3142** [comment]
不會的話就刪掉重創
