### ISSUE TITLE
heroku container:login登录不了

### ISSUE THREAD

**Issue by QiTianzu** [maple3142/heroku-aria2c#96]
在Win10上用Docker Machine提供docker环境，执行heroku container:login提示错误
error during connect: Get https://192.168.99.100:2376/v1.40/version: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 !    Login failed with: 1

**Comment by maple3142** [comment]
不知道
